# Generated by Django 5.0.1 on 2024-01-25 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='animation/images/')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
